# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfd22f28d35b0932553dc0d8edee5f430017e467edffe166fd90f342e55f5b8785f42fb331ebf166c6af657e9d145b9c990da0c4dfbe539c053ca15c3b6c9099
  Stripe_Publishable_key: 'pk_test_edwLiSD6H5j8Dqgn8uLTHyp3'
  Stripe_Secret_key: 'sk_test_LYsNdRba2pY36RhuvBDrGmvy'
  API_FB_KEY: "133380967242125"
  API_FB_APP_SECRET: "d84aef89614415d77d4d18752a6b14b7"
  API_GOOGLE_KEY: "93983628413-ul08d91klh12oilpqa87sh1so0nt8atq.apps.googleusercontent.com"
  API_GOOGLE_SECRET: "O2rooFNyXJ2SeGyDN_qhTYRW"
  API_TWITTER_KEY: "oS3NIqpin9m0p8AJlavCmfnXL"
  API_TWITTER_SECRET: "qZtVHVlMqTb7pKjcXtJp3Hp2DlXtvTCgxaYefsvcnWGcV4dTO4"

test:
  secret_key_base: 1c44f39aa51a443d3c4378cc8992f334ca9c4e1503f2bc9bf810440370bb6e09c77c9d23d374a60b8e19264499a3576d4756c4dfc7134f510a73bf43a379467b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  Stripe_Publishable_key: <%= ENV["Publishable_key"] %>
  Stripe_Secret_key: <%= ENV["Publishable_key"] %>
  API_FB_KEY: <%= ENV["FB_KEY"] %>
  API_FB_APP_SECRET: <%= ENV["FB_APP_SECRET"] %>
  API_GOOGLE_KEY: <%= ENV["SECRET_KEY_BASE"] %>
  API_GOOGLE_SECRET: <%= ENV["GOOGLE_KEY"] %>
  API_TWITTER_KEY: <%= ENV["TWITTER_KEY"] %>
  API_TWITTER_SECRET: <%= ENV["TWITTER_SECRET"] %>
